In [10]:
#Visualizing Lidar PCD and colorize points by heights

import open3d as o3d
import numpy as np
import random, os

#defining path of pcd
path = r"/home/ankit/Perception/HW1/data/sets/nuscenes/samples/LIDAR_TOP/"

#selecting a random file
random_file = random.choice([
    x for x in os.listdir(path)
    if os.path.isfile(os.path.join(path, x))
])
random_selected_file = (os.path.join(path, random_file)) 

#printing random file name
print('pcd being displayed is', random_file)

pcd_name=random_selected_file
scan=np.fromfile(pcd_name, dtype=np.float32)
points = scan.reshape((-1, 5))[:, :4]
print(points.shape)

dist=points[:,1]
height=points[:,2]
intensity=points[:,3]

color = np.zeros([len(height), 3])
color[:, 0] = height/10
color[:, 1] = 0.5
color[:, 2] = 0.5

print(color)

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points[:, :3])
pcd.colors = o3d.utility.Vector3dVector(color)

o3d.visualization.draw_geometries([pcd])

pcd being displayed is n015-2018-10-08-15-36-50+0800__LIDAR_TOP__1538984248948287.pcd.bin
(34688, 4)
[[-1.86588481e-01  5.00000000e-01  5.00000000e-01]
 [-1.86895221e-01  5.00000000e-01  5.00000000e-01]
 [-1.88016966e-01  5.00000000e-01  5.00000000e-01]
 ...
 [-1.82732518e-09  5.00000000e-01  5.00000000e-01]
 [-1.82732518e-09  5.00000000e-01  5.00000000e-01]
 [-1.82732518e-09  5.00000000e-01  5.00000000e-01]]
